//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.28 at 09:18:42 PM CDT 
//

package org.fiveloyds.cookbook.domain;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="seqNo" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "content" })
@XmlRootElement(name = "instruction")
public class Instruction {

	@XmlValue
	protected String content;
	@XmlAttribute(required = true)
	protected BigInteger seqNo;

	/**
	 * Gets the value of the content property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getContent() {
		return content;
	}

	/**
	 * Sets the value of the content property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setContent(String value) {
		this.content = value;
	}

	/**
	 * Gets the value of the seqNo property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getSeqNo() {
		return seqNo;
	}

	/**
	 * Sets the value of the seqNo property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setSeqNo(BigInteger value) {
		this.seqNo = value;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj instanceof Instruction == false) {
			return false;
		}
		if (this == obj) {
			return true;
		}
		Instruction rhs = (Instruction) obj;
		return new EqualsBuilder().appendSuper(super.equals(obj)).append(seqNo,
				rhs.seqNo).append(content, rhs.content).isEquals();

	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder(15, 35).append(seqNo).append(content)
				.toHashCode();

	}

	@Override
	public String toString() {
		return new ToStringBuilder(this).append("seqNo", seqNo).append(
				"content", content).toString();
	}
}
