//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.23 at 09:19:11 PM CDT 
//

package org.fiveloyds.cookbook.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ingredientSet" maxOccurs="unbounded"/>
 *         &lt;element ref="{}instruction" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="imgLoc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="author" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="title" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "ingredientSet", "instruction" })
@XmlRootElement(name = "recipe")
public class Recipe {

	@XmlElement(required = true)
	protected List<IngredientSet> ingredientSet;
	@XmlElement(required = true)
	protected List<InstructionSet> instructionSet;
	@XmlAttribute
	protected String imgLoc;
	@XmlAttribute
	protected String author;
	@XmlAttribute(required = true)
	protected String title;

	/**
	 * Gets the value of the ingredientSet property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the ingredientSet property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getIngredientSet().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link IngredientSet }
	 * 
	 * 
	 */
	public List<IngredientSet> getIngredientSet() {
		if (ingredientSet == null) {
			ingredientSet = new ArrayList<IngredientSet>();
		}
		return this.ingredientSet;
	}

	/**
	 * Gets the value of the instruction property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the instruction property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getInstruction().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Instruction }
	 * 
	 * 
	 */
	public List<InstructionSet> getInstruction() {
		if (instructionSet == null) {
			instructionSet = new ArrayList<InstructionSet>();
		}
		return this.instructionSet;
	}

	/**
	 * Gets the value of the imgLoc property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getImgLoc() {
		return imgLoc;
	}

	/**
	 * Sets the value of the imgLoc property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setImgLoc(String value) {
		this.imgLoc = value;
	}

	/**
	 * Gets the value of the author property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * Sets the value of the author property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAuthor(String value) {
		this.author = value;
	}

	/**
	 * Gets the value of the title property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * Sets the value of the title property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTitle(String value) {
		this.title = value;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj instanceof Recipe == false) {
			return false;
		}
		if (this == obj) {
			return true;
		}
		Recipe rhs = (Recipe) obj;
		return new EqualsBuilder().appendSuper(super.equals(obj)).append(title,
				rhs.title).append(ingredientSet, rhs.ingredientSet).append(
				instructionSet, rhs.instructionSet).append(author, rhs.author)
				.isEquals();

	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder(17, 37).append(title).append(ingredientSet)
				.append(instructionSet).append(ingredientSet).append(author)
				.toHashCode();

	}

	@Override
	public String toString() {
		return new ToStringBuilder(this).append(title).append(ingredientSet)
				.append(instructionSet).append(ingredientSet).append(author)
				.toString();
	}
}
