//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.23 at 09:19:11 PM CDT 
//

package org.fiveloyds.cookbook.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="units" use="required" type="{}cookingUnit" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="amount" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "ingredient")
public class Ingredient {

	@XmlAttribute(required = true)
	protected CookingUnit units;
	@XmlAttribute(required = true)
	protected String name;
	@XmlAttribute(required = true)
	protected double amount;

	/**
	 * Gets the value of the units property.
	 * 
	 * @return possible object is {@link CookingUnit }
	 * 
	 */
	public CookingUnit getUnits() {
		return units;
	}

	/**
	 * Sets the value of the units property.
	 * 
	 * @param value
	 *            allowed object is {@link CookingUnit }
	 * 
	 */
	public void setUnits(CookingUnit value) {
		this.units = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the amount property.
	 * 
	 */
	public double getAmount() {
		return amount;
	}

	/**
	 * Sets the value of the amount property.
	 * 
	 */
	public void setAmount(double value) {
		this.amount = value;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj instanceof Ingredient == false) {
			return false;
		}
		if (this == obj) {
			return true;
		}
		Ingredient rhs = (Ingredient) obj;
		return new EqualsBuilder().appendSuper(super.equals(obj)).append(name,
				rhs.name).append(amount, rhs.amount).append(units, rhs.units).isEquals();

	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder(13, 33).append(name).append(amount).append(units)
				.toHashCode();

	}

	@Override
	public String toString() {
		return new ToStringBuilder(this).append("name", name).append(
				"amount", amount).append("units", units).toString();

	}

}
